[package]
name = "jetbrains-toolbox-context-menu"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
env_logger = "0.11.5"
clap = { version = "4.5.21", features = ["derive", "color", "env", "usage", "help", "wrap_help", "unicode", "suggestions", "string"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = { version = "1.0.66" }
octocrate = { version = "2.0.1", features = ["markdown", "repos"] }
tokio = { version = "1.41.1", features = ["rt", "rt-multi-thread", "macros"] }
serde_yaml = "0.9.34+deprecated"

[target.'cfg(windows)'.dependencies]
winreg = "0.52.0"

[target.'cfg(mac)'.dependencies]